version: '2.1'
orbs:
  node: circleci/node@5.0.3
  codecov: codecov/codecov@3.2.4
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test_and_upload:
    jobs:
      - test
      - checkout
      - codecov/upload