version: '2.1'
orbs:
  node: circleci/node@5.0.3
  codecov: codecov/codecov@3.2.4
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload